### ISSUE TITLE
http: panic serving <ip>:<port>: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by imba-tjd** [claudiodangelis/qrcp#185]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

My reproducible environment:

* Win10 20H2 x64 + qrcp_0.7.0_Windows_x86_64.tar.gz
* WSL Debian 10 + qrcp_0.7.0_linux_x86_64.tar.gz
* VM Debian 10 x86 + qrcp_0.7.0_linux_i386.tar.gz

```
./qrcp test.txt -k
Scan the following URL with a QR reader to start the file transfer:
http://192.168.1.104:53817/send/yl0w
<qrcode>
```

Use `curl http://192.168.1.104:53817/send/yl0w` twice:

```
2020/12/06 13:48:11 http: panic serving 192.168.1.104:53821: sync: negative WaitGroup counter
goroutine 33 [running]:
net/http.(*conn).serve.func1(0xc0000bc000)
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:1800 +0x139
panic(0x861640, 0x9f6130)
        /opt/hostedtoolcache/go/1.14.9/x64/src/runtime/panic.go:975 +0x3e3
sync.(*WaitGroup).Add(0xc00040c320, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.14.9/x64/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(0xc00040c320)
        /opt/hostedtoolcache/go/1.14.9/x64/src/sync/waitgroup.go:99 +0x34
github.com/claudiodangelis/qrcp/server.New.func2(0xa07120, 0xc0000c8000, 0xc0000be000)
        /home/runner/work/qrcp/qrcp/server/server.go:207 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc000410f30, 0xa07120, 0xc0000c8000, 0xc0000be000)
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xd427c0, 0xa07120, 0xc0000c8000, 0xc0000be000)
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0003ec000, 0xa07120, 0xc0000c8000, 0xc0000be000)
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0000bc000, 0xa08060, 0xc0000b0180)
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.14.9/x64/src/net/http/server.go:2962 +0x35c
```

**Comment by claudiodangelis** [comment]
Thanks, will have a look soon!

**Comment by claudiodangelis** [comment]
Hello @imba-tjd  this should be fixed now.
Can you please confirm? Thanks!

**Comment by claudiodangelis** [comment]
Fixed now, thanks again for reporting!
C
